-- return {
--   {
--     "catppuccin/nvim",
--     lazy = false,
--     name = "catppuccin",
--     priority = 1000,
--     flavour = "macchiato",
--     config = function()
--       vim.cmd.colorscheme "catppuccin-macchiato"
--     end
--   }
-- }
